### ISSUE TITLE
Announcement menu is not shown for users with Developer role

### ISSUE THREAD

**Issue by kvniranjan** [mantisbt-plugins/Announce#14]
Hi,
I have installed the Announcement plugin,and it works like a Charm.However even though in the configuration option I have given the rights to "Developer" role,the announcements tab is not appearing for the Developer profile.
Kindly check.

**Comment by dregad** [comment]
You actually need to configure your system so that `$g_manage_site_threshold` is set to a value lower than or equal to the plugin's threshold (*DEVELOPER* in your case), to authorize those users to access the *Manage* menu.

Otherwise, the users must access the page directly via http://path.to/mantisbt/plugin.php?page=Announce/list

I'll modify the config page to display a warning in this case.
