### ISSUE TITLE
images not showing

### ISSUE THREAD

**Issue by cs97jjm3** [mantisbt-plugins/Announce#24]
non of the images are showing? 

link url says http://f1cs97jjm3.ddns.net/mantis/plugin_file.php?file=Announce/delete.png

**Comment by dregad** [comment]
@cs97jjm3 I don't understand what your problem is. Please provide a more detailed description, explain what you get vs what you expect, maybe a screenshot illustrating.

**Comment by cs97jjm3** [comment]
the dismiss.png ,add.png and delete.png don not show when i enable the plugin, i have hard coded for all for now..eg.

<a class="announce_add_context" href="#" value="<?php echo $message_id ?>">
										<img src="http://f1cs97jjm3.ddns.net/mantis/plugins/Announce/files/add.png" alt="+" border="0"/>
									</a>
								</td>

**Comment by dregad** [comment]
I'm sorry but I'm not able to reproduce the problem with the given information.

**Comment by cs97jjm3** [comment]
just reinstalled everything and i get following : I think problem is with folder permissions

![1](https://user-images.githubusercontent.com/6145730/36329881-80eb3a70-135f-11e8-81b5-6262b61f5208.PNG)
![2](https://user-images.githubusercontent.com/6145730/36329882-81012452-135f-11e8-869c-dc88cd6e296b.PNG)

**Comment by dregad** [comment]
As mentioned previously, I can't reproduce the problem on my end.

The link to the image is generated by MantisBT's plugin API, e.g. `/mantis/plugin_file.php?file=Announce/delete.png`  -> http://f1cs97jjm3.ddns.net/mantis/plugin_file.php?file=Announce/delete.png (per your initial report). When I click that URL, I get an error message saying that the image _cannot be displayed because it contains errors_. Maybe the image files are corrupt on your server ?

If indeed it's a permissions problem, there's not much I can do to help and you'll need to fix your server's config yourself.
